### ISSUE TITLE
Example appears not working

### ISSUE THREAD

**Issue by josedesoto** [IdentityPython/pysaml2#237]
After install everything and pass all the tests, I am trying to see how the examples works:
- example/idp2
- example/sp-wsgi

I have run the command `./all.sh start` and everything looks fine. No errors are displayed and the IDP is running in the port 8088 and the SP in 8087. After run the URL: _http://localhost:8087_ I can see how the SP redirects to the IDP where the browser display the form to introduce the user and the password. In this step _idp.log_ shows the next errors:

```
2015-07-08 17:11:09,640 saml2.sigver:DEBUG ==== Certs from metadata ==== None: [(<open file '<fdopen>', mode 'w+b' at 0x7f7967a62c90>, '/tmp/tmpfbbwV7.pem')] ====
2015-07-08 17:11:09,641 saml2.sigver:DEBUG xmlsec command: /usr/bin/xmlsec1 --verify --pubkey-cert-pem /tmp/tmpfbbwV7.pem --id-attr:ID urn:oasis:names:tc:SAML:2.0:protocol:AuthnRequest --store-signatures --node-id id-FITgiINxgEWzl5TRL --output /tmp/tmpBCbfkU.xml /tmp/tmpIo395A.xml
2015-07-08 17:11:09,678 saml2.sigver:ERROR
....
/tmp/tmpIo395A.xml:1: parser error : Start tag expected, '<' not found
nVZZk6o4FH6/v8LiPlrdBNR2qWtPhVXUoGDE5Q0xLApECYj664fW22v13JqZx/PlrN85Ocmvv85JXDuR
^
Error: failed to parse xml file "/tmp/tmpIo395A.xml"
Error: failed to load document "/tmp/tmpIo395A.xml"
ERROR
SignedInfo References (ok/all): 0/0
Manifests References (ok/all): 0/0
Error: failed to verify file "/tmp/tmpIo395A.xml
```

Note: The IDP does not create any of the _/tmp/..._ files.

When I introduce the user and the password, for example: roland / dianakra  the IDP display the next exceptions:

```
127.0.0.1 - - [08/Jul/2015 17:14:52] "POST /verify HTTP/1.1" 302 438
127.0.0.1 - - [08/Jul/2015 17:14:52] "GET /sso/redirect?id=HavNriDUIVxIm0fTmnXwZx9D&key=bc7f78d00f608903e9f825593bbbff32298aba12 HTTP/1.1" 200 47
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 204, in write
    assert type(data) is StringType,"write() argument must be string"
AssertionError: write() argument must be string
127.0.0.1 - - [08/Jul/2015 17:14:52] "GET /sso/redirect?id=HavNriDUIVxIm0fTmnXwZx9D&key=bc7f78d00f608903e9f825593bbbff32298aba12 HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 59521)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 131, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 92, in run
    self.close()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 33, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```

Does anyone has the same problem?
Using Ubuntu 15.04 with Python 2.7

**Comment by rvanlaar** [comment]
Confirmed, with git checkout: e341cdc5fe2f0a0c47b94c1a58d38ac03786db34

**Comment by josedesoto** [comment]
I have done a few more tests and it looks an issue in the SP code. Testing the PYSAML2 IDP example with a SP developed with web2py framework works fine, here more details:

https://github.com/josedesoto/web2py-sp-example#test-web2py-sp-with-pysaml2-example-idp

**Comment by peppelinux** [comment]
Time passed, things changed. Hope that you hot It working. I have my implementation of both do and idp, in djangosaml2 and uniAuth. Let uso know
