### ISSUE TITLE
human readable description of AssertionError

### ISSUE THREAD

**Issue by spaceone** [IdentityPython/pysaml2#254]
It would be helpful if the AssertionError contains a human readable error message so that it can be presented to the client.

```
Traceback (most recent call last):
    response = self.sp.parse_authn_request_response(message, binding, self.outstanding_queries, self.outstanding_certs)
  File "/usr/lib/python2.7/dist-packages/saml2/client_base.py", line 573, in parse_authn_request_response
    binding, **kwargs)
  File "/usr/lib/python2.7/dist-packages/saml2/entity.py", line 949, in _parse_response
    response = response.verify(key_file)
  File "/usr/lib/python2.7/dist-packages/saml2/response.py", line 853, in verify
    res = self._verify()
  File "/usr/lib/python2.7/dist-packages/saml2/response.py", line 391, in _verify
    assert self.issue_instant_ok()
AssertionError
```

**Comment by spaceone** [comment]
Best would be exceptions for each error type, e.g. ResponseLifetimeExceed.

**Comment by rohe** [comment]
Agree, it's on my list of things to do. Unfortunately it's been there for a while.

**Comment by spaceone** [comment]
Even worse is raising of `Exception` itself. This cannot be handled without checking str(exc).
```
    response = self.sp.parse_authn_request_response(message, binding, self.outstanding_queries, self.outstanding_certs)
  File "/usr/lib/python2.7/dist-packages/saml2/client_base.py", line 573, in parse_authn_request_response
    binding, **kwargs)
  File "/usr/lib/python2.7/dist-packages/saml2/entity.py", line 949, in _parse_response
    response = response.verify(key_file)
  File "/usr/lib/python2.7/dist-packages/saml2/response.py", line 864, in verify
    if self.parse_assertion(key_file):
  File "/usr/lib/python2.7/dist-packages/saml2/response.py", line 838, in parse_assertion
    if not self._assertion(assertion, assertion in res):
  File "/usr/lib/python2.7/dist-packages/saml2/response.py", line 772, in _assertion
    if not self.condition_ok():
  File "/usr/lib/python2.7/dist-packages/saml2/response.py", line 576, in condition_ok
    validate_before(conditions.not_before, self.timeslack)
  File "/usr/lib/python2.7/dist-packages/saml2/validate.py", line 97, in validate_before
    raise Exception("Can't use it yet %d <= %d" % (nbefore, now))
Exception: Can't use it yet 1441897487 <= 1441868284
```

**Comment by sheilatron** [comment]
I bumped into this while testing an older version, and the broad exception raising seems to have been corrected in newer versions along with adding a "slack" factor. Here is the fix commit from @knaperek :

https://github.com/IdentityPython/pysaml2/commit/9a3b3849df2b8a337f9d130de68024fec13363ee#diff-b22d07287a1f7d4a4ae80402fa1bd832

**Comment by sheilatron** [comment]
I bumped into this confusing error while testing an older version, and the broad exception raising seems to have been corrected in newer versions. Here is the fix commit from @rohe 

https://github.com/IdentityPython/pysaml2/commit/5518bd69f572600eea035c5b9958354ea11b58e0#diff-b22d07287a1f7d4a4ae80402fa1bd832

**Comment by c00kiemon5ter** [comment]
I am closing this, as it has been fixed. Thanks for looking into this.
