### ISSUE TITLE
Static file handlers of example servers break w/ recent CherryPy (return unicode instead of bytes)

### ISSUE THREAD

**Issue by jgehrcke** [IdentityPython/pysaml2#368]
The example servers in this repository are affected by the same issue as described here: https://github.com/rohe/pyoidc/issues/232

Example traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 1408, in communicate
    req.respond()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 862, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/__init__.py", line 2337, in respond
    raise ValueError('WSGI Applications must yield bytes')
ValueError: WSGI Applications must yield bytes
```

From a user agent's pov this can be the result:

```
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by c00kiemon5ter** [comment]
I am closing this as #369 has been merged
