### ISSUE TITLE
4.6.0 version is set incorrectly

### ISSUE THREAD

**Issue by jberkz** [IdentityPython/pysaml2#535]
When installing with pip, the returned version is `file-VERSION` and not `4.6.0`

## Code Version
Active version: 4.6.0

## Expected Behavior
```
>>>import saml2; print(saml2.__version__)
4.6.0
```

## Current Behavior
```
>>>import saml2; print(saml2.__version__)
file-VERSION
```

## Steps to Reproduce

```
pip show pysaml2
# --or--
import saml2; print(saml2.__version__)
```

**Comment by pquentin** [comment]
When trying `pip install pysaml2` with pip 18, I get the following:

```
Collecting pysaml2
Installing collected packages: pysaml2
Exception:
Traceback (most recent call last):
  File "/venv/lib/python3.5/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/venv/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 347, in run
    use_user_site=options.use_user_site,
  File "/venv/lib/python3.5/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/venv/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 941, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/venv/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 526, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/venv/lib/python3.5/site-packages/pip/_internal/wheel.py", line 326, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: pysaml2 .dist-info directory not found
```

Is this expected?

**Comment by c00kiemon5ter** [comment]
Hi and thanks for reporting this. I have tested with both `python2` and `python3` and it works as expected. I am guessing you are using an older version of `setuptools` that is responsible for packaging `pysaml2` and is causing this.

My current virtualenv with python2:
```
(venv:py2)$ pip list
Package         Version  
--------------- ---------
asn1crypto      0.24.0   
certifi         2018.4.16
cffi            1.11.5   
chardet         3.0.4    
cryptography    2.3      
defusedxml      0.5.0    
enum34          1.1.6    
future          0.16.0   
idna            2.7      
ipaddress       1.0.22   
pip             18.0     
pycparser       2.18     
pyOpenSSL       18.0.0   
pysaml2         4.6.0    
python-dateutil 2.7.3    
pytz            2018.5   
requests        2.19.1   
setuptools      40.0.0   
six             1.11.0   
urllib3         1.23     
wheel           0.31.1
```

and with python3:
```
(venv:py3)$ pip list 
Package         Version  
--------------- ---------
asn1crypto      0.24.0   
certifi         2018.4.16
cffi            1.11.5   
chardet         3.0.4    
cryptography    2.3      
defusedxml      0.5.0    
enum34          1.1.6    
future          0.16.0   
idna            2.7      
ipaddress       1.0.22   
pip             18.0     
pycparser       2.18     
pyOpenSSL       18.0.0   
pysaml2         4.6.0    
python-dateutil 2.7.3    
pytz            2018.5   
requests        2.19.1   
setuptools      40.0.0   
six             1.11.0   
urllib3         1.23     
wheel           0.31.1
```

Could you please post the python and the `setuptools` version you are using, and then try upgrading `setuptools`?

**Comment by harpunius** [comment]
I confirm. If installed with pip, the package is installed as `pysaml2-VERSION`.

**Comment by pquentin** [comment]
@c00kiemon5ter I'll open a new issue, sorry that I hijacked this one. (And thanks for pysaml2!)

**Comment by jberkz** [comment]
I can confirm updating setuptools to 40.0.0 resolved this issue. Thanks!

**Comment by pquentin** [comment]
The minimum supported setuptools version is actually [setuptools 39.2.0](http://setuptools.readthedocs.io/en/latest/history.html#v39-2-0) which adds support for "file:". The error I reported above was using a devpi server instead of PyPI. To fix it, I had to upgrade setuptools but also remove the bad wheel from the pip cache.
