### ISSUE TITLE
ValueError("Type and value doesn't match") in correctly_signed_response()

### ISSUE THREAD

**Issue by jdavisturak** [IdentityPython/pysaml2#544]
Code: v4.6.1

I am working on an SP-initiated flow.  I have configured much it (finally), but my response from the IDP does not seem to be parsing correctly. 

My intuition is that the SAML ought to encode for Deflated XML, but in this case it is not deflated, since when I paste it in  https://www.samltool.com/decode.php I see plaintext XML in the field that says "Deflated XML".

If this is indeed the issue, I will have something to work with.  Any help will be appreciated!

Thanks!

Below is the Traceback:

```
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/client_base.py", line 702, in parse_authn_request_response
     binding, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/entity.py", line 1142, in _parse_response
     response = response.loads(xmlstr, False, origxml=origxml)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/response.py", line 512, in loads
     self._loads(xmldata, decode, origxml)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/response.py", line 337, in _loads
     **args)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/sigver.py", line 1636, in correctly_signed_response
     response = samlp.any_response_from_string(decoded_xml)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/samlp.py", line 1847, in any_response_from_string
     resp = func(xmlstr)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/samlp.py", line 1620, in response_from_string
     return saml2.create_class_from_xml_string(Response, xml_string)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/__init__.py", line 97, in create_class_from_xml_string
     return create_class_from_element_tree(target_class, tree)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/__init__.py", line 127, in create_class_from_element_tree
     target.harvest_element_tree(tree)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/__init__.py", line 315, in harvest_element_tree
     self._convert_element_tree_to_member(child)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/__init__.py", line 485, in _convert_element_tree_to_member
     create_class_from_element_tree(member_class[0], child_tree))
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/__init__.py", line 127, in create_class_from_element_tree
     target.harvest_element_tree(tree)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/__init__.py", line 315, in harvest_element_tree
     self._convert_element_tree_to_member(child)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/__init__.py", line 485, in _convert_element_tree_to_member
     create_class_from_element_tree(member_class[0], child_tree))
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/__init__.py", line 127, in create_class_from_element_tree
     target.harvest_element_tree(tree)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/__init__.py", line 315, in harvest_element_tree
     self._convert_element_tree_to_member(child)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/__init__.py", line 485, in _convert_element_tree_to_member
     create_class_from_element_tree(member_class[0], child_tree))
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/__init__.py", line 127, in create_class_from_element_tree
     target.harvest_element_tree(tree)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/__init__.py", line 315, in harvest_element_tree
     self._convert_element_tree_to_member(child)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/__init__.py", line 485, in _convert_element_tree_to_member
     create_class_from_element_tree(member_class[0], child_tree))
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/__init__.py", line 127, in create_class_from_element_tree
     target.harvest_element_tree(tree)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/saml.py", line 274, in harvest_element_tree
     self.set_text(tree.text)
   File "/usr/local/lib/python2.7/dist-packages/pysaml2-file_VERSION-py2.7.egg/saml2/saml.py", line 227, in set_text
     raise ValueError("Type and value doesn't match")
 ValueError: Type and value doesn't match
```

**Comment by c00kiemon5ter** [comment]
Hi,

From the backtrace we cannot know what the type and value that don't match are, but my guess is that the type is probably `anyType`. This is probably related to #539 and #543 which will hopefully be addressed soon.

On another note, `pysaml2` hasn't been installed correctly, as I can see that the version hasn't been resolved - it should be `pysaml2-X.Y.Z-...` instead of `pysaml2-file_VERSION-...`. Please, update `setuptools` (`pip install -U setuptools`) and reinstall `pysaml2`.

**Comment by jdavisturak** [comment]
Indeed duplicate of (issue attempted to be fixed by commit) #543 

Snippet below worked.  Also commented in #543.

```
diff --git a/src/saml2/saml.py b/src/saml2/saml.py
index 023f352..df23c92 100644
--- a/src/saml2/saml.py
+++ b/src/saml2/saml.py
@@ -223,6 +223,8 @@ class AttributeValueBase(SamlBase):
                             _ = float(val)
                         elif typ == "xs:base64Binary":
                             pass
+                        elif typ == "xs:anyType":
+                            pass
                         else:
                             raise ValueError("Type and value doesn't match")
             elif isinstance(val, bool):
```

**Comment by djmm68** [comment]
Hi, we're trying to implement authentication via djangosaml2 in our project, which includes eidas attributes that our idp requires. The problem we find is that, after sending the authrrequest by saml, we get a 401 error (unauthorized), and reviewing the log, it reports:
```
ValueError: Type and value do not match: LegalPersonIdentifierType:<class 'str'>:12345678X
Forbidden: /saml2/acs/
```
Applying the solution commented by @jdavisturak , it works. But that implies modifying the library. Is it possible to map or treat such attributes somehow in the project's settings.py configuration file, without having to alter the library?

**Comment by c00kiemon5ter** [comment]
hello @djmm68, can you create a failing test case for this? that will make it easier to understand the issue you're facing and where this stems from.

Including also (part of) the XML response with this attribute would also be good. Mask any values of course, what I'm more interested in is the structure and format.

**Comment by djmm68** [comment]
Thanks @c00kiemon5ter  for your interest..., a test case? of course!
We make a request against the idp, and we get a 401: access denied error. We include the saml-tracer report and settings.py django config file (saml part).
**SAML REQUEST**
```
HTTP:
POST __URL__?IdSesion=id-__NUM__ HTTP/1.1
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Upgrade-Insecure-Requests: 1
Origin: __URL__:1443
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-Dest: document
Referer: __URL_LOGIN__
Accept-Encoding: gzip, deflate, br
Accept-Language: es,en-US;q=0.9,en;q=0.8
Cookie: JSESSIONID__NUM__
HTTP/1.1 200 OK
Date: Fri, 03 Jun 2022 07:44:48 GMT
X-Powered-By: Servlet/3.1
X-OneAgent-JS-Injection: true
Timing-Allow-Origin: *
Server-Timing: dtSInfo;desc="0", dtRpid;desc="__NUM__", dtTao;desc="1"
Keep-Alive: timeout=5, max=196
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8
Content-Language: es-ES

Parameters:
POST
RelayState: _Vh4eYr6-
SAMLResponse: __RESPONSE__

SAML:
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"
                 xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
                 xmlns:eidas="http://eidas.europa.eu/attributes/naturalperson"
                 xmlns:eidas-legal="http://eidas.europa.eu/attributes/legalperson"
                 xmlns:eidas-natural="http://eidas.europa.eu/attributes/naturalperson"
                 xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
                 xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 Consent="urn:oasis:names:tc:SAML:2.0:consent:obtained"
                 Destination="__URL_LOGIN__?IdSesion=id-__NUM__"
                 ID="__NUM__"
                 InResponseTo="__ID__"
                 IssueInstant="__DATE_TIME__"
                 Version="2.0"
                 >
    <saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">__ISSUER__</saml2:Issuer>
    <ds:Signature>
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
            <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha512" />
            <ds:Reference URI="__URI__">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                        <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"
                                                PrefixList="eidas-legal eidas-natural xs"/>
                    </ds:Transform>
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512" />
                <ds:DigestValue>__VALUE__</ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>__SIGNATURE__</ds:SignatureValue>
        <ds:KeyInfo>
            <ds:X509Data>
                <ds:X509Certificate>__CERTIFICATE__</ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature>
    <saml2p:Status>
        <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
        <saml2p:StatusMessage>urn:oasis:names:tc:SAML:2.0:status:Success</saml2p:StatusMessage>
    </saml2p:Status>
    <saml2:Assertion ID="__ID__" IssueInstant="__DATE_TIME__" Version="2.0">
        <saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">OUR_ISSUER</saml2:Issuer>
        <saml2:Subject>
            <saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
                          NameQualifier="__ISSUER__"
                          >__ID__</saml2:NameID>
            <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml2:SubjectConfirmationData Address="__IP__" InResponseTo="id-__NUM__" NotOnOrAfter="__DATE_TIME__"
                                               Recipient="__URL__?IdSesion=id-__NUM__"/>
            </saml2:SubjectConfirmation>
        </saml2:Subject>
        <saml2:Conditions NotBefore="__DATE_TIME__" NotOnOrAfter="__DATE_TIME__">
            <saml2:AudienceRestriction>
                <saml2:Audience>__URL__?IdSesion=id-__NUM__</saml2:Audience>
            </saml2:AudienceRestriction>
        </saml2:Conditions>
        <saml2:AuthnStatement AuthnInstant="__DATE_TIME__">
            <saml2:AuthnContext>        <saml2:AuthnContextClassRef>http://eidas.europa.eu/LoA/substantial</saml2:AuthnContextClassRef>
                <saml2:AuthnContextDecl/>
            </saml2:AuthnContext>
        </saml2:AuthnStatement>
        <saml2:AttributeStatement>
            <saml2:Attribute FriendlyName="LegalPersonIdentifier"
                             Name="http://eidas.europa.eu/attributes/legalperson/LegalPersonIdentifier"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="eidas-legal:LegalPersonIdentifierType"
                                      >__ID__</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="FamilyName"
                             Name="http://eidas.europa.eu/attributes/naturalperson/CurrentFamilyName"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="eidas-natural:CurrentFamilyNameType"
                                      >__FAMILY_NAME__</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="FirstName"
                             Name="http://eidas.europa.eu/attributes/naturalperson/CurrentGivenName"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="eidas-natural:CurrentGivenNameType"
                                      >__FIRST_NAME__</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="PersonIdentifier"
                             Name="http://eidas.europa.eu/attributes/naturalperson/PersonIdentifier"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="eidas-natural:PersonIdentifierType"
                                      >__PERSON_ID__</saml2:AttributeValue>
            </saml2:Attribute>
        </saml2:AttributeStatement>
    </saml2:Assertion>
</saml2p:Response>

Summary:
SAML2.0 Response
Destination	__URL__?IdSesion=id-__NUM__
ID	__ID__
Version	2.0
IssueInstant	__DATE_TIME__
Issuer	OUR_ISSUER
SAML 2.0 Assertion
ID	__ID__
Version	2.0
IssueInstant	__DATE_TIME__
Subject	__ID__
SAML 2.0 AttributeStatement
http://eidas.europa.eu/attributes/legalperson/LegalPersonIdentifier	__ID__
http://eidas.europa.eu/attributes/naturalperson/CurrentFamilyName	__FAMILY_NAME__
http://eidas.europa.eu/attributes/naturalperson/CurrentGivenName	__GIVEN_NAME__
http://eidas.europa.eu/attributes/naturalperson/PersonIdentifier	__PERSON_ID__
```
**SAML Response**
```
HTTP:
POST __URL_POST__ HTTP/1.1
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Upgrade-Insecure-Requests: 1
Origin: null
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: navigate
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br
Accept-Language: es,en-US;__NUM__
HTTP/1.1 403 Forbidden
Date: Fri, 03 Jun 2022 07:44:48 GMT
Server: WSGIServer/0.2 CPython/3.9.7
Content-Type: text/html; charset=utf-8
Vary: Cookie
X-Frame-Options: DENY
Content-Length: 10735
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: same-origin
Server-Timing: __SERVER_TIMING__
Set-Cookie: saml_session=__NUM__; HttpOnly; Path=/; SameSite=None; Secure
Set-Cookie: csrftoken=__TOKEN__; expires=__DATE_TIME__; Max-Age=__NUM__; Path=/; SameSite=Lax

Parameters:
POST
RelayState: /
SAMLResponse: __RESPONSE__

SAML:
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"
                 xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
                 xmlns:eidas="http://eidas.europa.eu/attributes/naturalperson"
                 xmlns:eidas-legal="http://eidas.europa.eu/attributes/legalperson"
                 xmlns:eidas-natural="http://eidas.europa.eu/attributes/naturalperson"
                 xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
                 xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 Consent="urn:oasis:names:tc:SAML:2.0:consent:obtained"
                 Destination="__URL_DESTINATION__"
                 ID="__ID__"
                 InResponseTo="id-__NUM__"
                 IssueInstant="__DATE_TIME__"
                 Version="2.0"
                 >
    <saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">__ISSUER__</saml2:Issuer>
    <ds:Signature>
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
            <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha512" />
            <ds:Reference URI="__URI__">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                        <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"
                                                PrefixList="eidas-legal eidas-natural xs"/>
                    </ds:Transform>
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512" />
                <ds:DigestValue>__VALUE__</ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>__SIGNATURE__</ds:SignatureValue>
        <ds:KeyInfo>
            <ds:X509Data>
                <ds:X509Certificate>__CERTIFICATE__</ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature>
    <saml2p:Status>
        <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
        <saml2p:StatusMessage>urn:oasis:names:tc:SAML:2.0:status:Success</saml2p:StatusMessage>
    </saml2p:Status>
    <saml2:Assertion ID="__ID__"
                     IssueInstant="__DATETIME__"
                     Version="2.0">
        <saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">__ISSUER__</saml2:Issuer>
        <saml2:Subject>
            <saml2:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
                          NameQualifier="__ISSUER__"
                          >__ID__</saml2:NameID>
            <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml2:SubjectConfirmationData Address="__IP__"
                                               InResponseTo="id-__NUM__"
                                               NotOnOrAfter="__DATETIME__"
                                               Recipient="__URL_ACS__"
                                               />
            </saml2:SubjectConfirmation>
        </saml2:Subject>
        <saml2:Conditions NotBefore="__DATETIME__"
                          NotOnOrAfter="__DATETIME__"
                          >
            <saml2:AudienceRestriction>
                <saml2:Audience>__URL_ACS__</saml2:Audience>
            </saml2:AudienceRestriction>
        </saml2:Conditions>
        <saml2:AuthnStatement AuthnInstant="__DATETIME__">
            <saml2:AuthnContext>
                <saml2:AuthnContextClassRef>http://eidas.europa.eu/LoA/substantial</saml2:AuthnContextClassRef>
                <saml2:AuthnContextDecl/>
            </saml2:AuthnContext>
        </saml2:AuthnStatement>
        <saml2:AttributeStatement>
            <saml2:Attribute FriendlyName="LegalPersonIdentifier"
                             Name="http://eidas.europa.eu/attributes/legalperson/LegalPersonIdentifier"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="eidas-legal:LegalPersonIdentifierType"
                                      >__PERSON_ID__</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="FamilyName"
                             Name="http://eidas.europa.eu/attributes/naturalperson/CurrentFamilyName"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="eidas-natural:CurrentFamilyNameType"
                                      >__FAMILY_NAME__</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="FirstName"
                             Name="http://eidas.europa.eu/attributes/naturalperson/CurrentGivenName"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="eidas-natural:CurrentGivenNameType"
                                      >__GIVEN_NAME__</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="PersonIdentifier"
                             Name="http://eidas.europa.eu/attributes/naturalperson/PersonIdentifier"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="eidas-natural:PersonIdentifierType"
                                      >__PERSON_ID__</saml2:AttributeValue>
            </saml2:Attribute>
        </saml2:AttributeStatement>
    </saml2:Assertion>
</saml2p:Response>

Summary:
SAML2.0 Response
Destination	__URL_DESTINATION__
ID	__ID__
Version	2.0
IssueInstant	__DATE_TIME__
Issuer	__ISSUER__
SAML 2.0 Assertion
ID	__ID__
Version	2.0
IssueInstant	__DATE_TIME__
Subject	__PERSON_ID__
SAML 2.0 AttributeStatement
http://eidas.europa.eu/attributes/legalperson/LegalPersonIdentifier	__PERSON_ID__
http://eidas.europa.eu/attributes/naturalperson/CurrentFamilyName	__FAMILY_NAME__
http://eidas.europa.eu/attributes/naturalperson/CurrentGivenName	__GIVEN_NAME__
http://eidas.europa.eu/attributes/naturalperson/PersonIdentifier	__PERSON_ID__
```
**settings.py**
```
SAML_SESSION_COOKIE_NAME = 'saml_session'
SESSION_COOKIE_SECURE = True

AUTHENTICATION_BACKENDS = (
    'djangosaml2.backends.Saml2Backend',
    'django.contrib.auth.backends.ModelBackend',
)

SAML_ALLOWED_HOSTS = []
SAML_DEFAULT_BINDING = saml2.BINDING_HTTP_POST
SAML_LOGOUT_REQUEST_PREFERRED_BINDING = saml2.BINDING_HTTP_POST
SAML_IGNORE_LOGOUT_ERRORS = False
SAML_DJANGO_USER_MAIN_ATTRIBUTE = 'email'
SAML_DJANGO_USER_MAIN_ATTRIBUTE_LOOKUP = '__iexact'
SAML_ATTRIBUTE_MAPPING = {    
    'http://__URL__.sso/UserCode': ('username'),
    'http://__URL__.sso/Mail': ('email'),
    'http://eidas.europa.eu/attributes/naturalperson/CurrentGivenName': ('first_name'),
    'http://__URL__.key/FirstSurname': ('last_name'),
}
SAML_CREATE_UNKNOWN_USER = True

SAML_CONFIG = {
  'xmlsec_binary': '/usr/bin/xmlsec1',
  'accepted_time_diff': 60,
  "name": "__NAME__",
  'entityid': '__URL_ACS__',
  'allow_unknown_attributes': True,

  'service': {
      'sp' : {
          'name': '__NAME__',
        
          "logout_requests_signed": True,

          'endpoints': {
              'assertion_consumer_service': [
                  ('__URL_ACS__',
                   saml2.BINDING_HTTP_POST),
                  ],
              'single_logout_service': [
                  ('__URL_POST__',
                   saml2.BINDING_HTTP_POST),
                  ],
              },

          'signing_algorithm':  saml2.xmldsig.SIG_RSA_SHA256,
          'digest_algorithm':  saml2.xmldsig.DIGEST_SHA256,
          'force_authn': True,
          'name_id_format_allow_create': True,
          "requested_attributes": [
                 {
                    "name_format": "urn:oasis:names:tc:SAML:2.0:attrname-format:uri",
                    "friendly_name": "IPMDIdP",
                    "name": "__URL_IDP__",
                    "required": True,
                 },


           ],

          'want_response_signed': True,
          'authn_requests_signed': True,
          'want_assertions_signed': False,
          'only_use_keys_in_metadata': True,
          'allow_unsolicited': False,
          'idp': {
              'IPMDIdP': {
                 'single_sign_on_service': {
                    saml2.BINDING_HTTP_POST: '__URL_LOGIN__',
                     },

                  },
                },
          },
      },

  'metadata': { 'local': [path.join(BASE_DIR, 'remote_metadata.xml')], },
  'debug': 1,
  'key_file': path.join(BASE_DIR, 'private.key'),  # private part
  'cert_file': path.join(BASE_DIR, 'public.pem'),  # public part
  'encryption_keypairs': [{
      'key_file': path.join(BASE_DIR, 'private.key'),  # private part
      'cert_file': path.join(BASE_DIR, 'public.pem'),  # public part
  }],
}
```
On the other hand, modifying the pysaml2 library (just to include data types not recognized by the library), it works. The modified files are:

/opt/app-root/lib/python3.9/site-packages/saml2/saml.py
Added:
```
'LegalPersonIdentifierType': {
                'type': str,
                'to_type': str,
                'to_text': (
                    lambda x: base64.encodebytes(x.encode()) if base64encode else x
                ),
            },
            'CurrentFamilyNameType': {
                'type': str,
                'to_type': str,
                'to_text': (
                    lambda x: base64.encodebytes(x.encode()) if base64encode else x
                ),
            },
            'CurrentGivenNameType': {
                'type': str,
                'to_type': str,
                'to_text': (
                    lambda x: base64.encodebytes(x.encode()) if base64encode else x
                ),
            },
            'PersonIdentifierType': {
                'type': str,
                'to_type': str,
                'to_text': (
                    lambda x: base64.encodebytes(x.encode()) if base64encode else x
                ),
            },

```
/opt/app-root/lib64/python3.9/site-packages/xmlschema/validators/global_maps.py
Added:
```
if qname.__contains__("LegalPersonIdentifier"):
                qname = '{http://www.w3.org/2000/09/xmldsig#}ObjectType'
            if qname.__contains__("CurrentFamily"):
                qname = '{http://www.w3.org/2000/09/xmldsig#}ObjectType'
            if qname.__contains__("CurrentGiven"):
                qname = '{http://www.w3.org/2000/09/xmldsig#}ObjectType'
            if qname.__contains__("PersonIdentifier"):
                qname = '{http://www.w3.org/2000/09/xmldsig#}ObjectType'
            obj = self.types[qname]
```
But the point here is that we want to avoid modifying the library; but we don't know how to map the eidas attributes to solve the unrecognized data type error, and pass the auth; if that is possible under current conditions.

**Comment by c00kiemon5ter** [comment]
I've changed the behaviour for pysaml2 to fallback to string when the type cannot be processed. See, 348a78179207da3a9547913e6b6616c8c4daedf3.

According to the eIDAS spec, most of the eidas-defined types are based on `xsd:string`. Certain types are special though:
- `DateOfBirthType` is based on `xsd:date`
- `CurrentAddress` and `LegalAddress` are encoded as multiple `xsd:string` elements, as a base64 payload
- `Gender` is a string but restricted to one of `Male`, `Female`, `Unspecified`

for those we need to add special handling.

**Comment by djmm68** [comment]
Great! Applying that commit removes the unrecognized data type errors. We have already incorporated the new version of the library to our project.
Thank you very much for your support.

**Comment by c00kiemon5ter** [comment]
Good to hear that @djmm68. I will be updating the library for the specific types from eidas, for completeness sake. I will ping you if you are available to check when that's in place.

**Comment by djmm68** [comment]
Hi again! We have a question regarding the validation of the **xmlschema.** Once the issue that generated an error in authentication due to unrecognized data types has been resolved, we now find that the xmlschema validator that the **pysaml2** library calls doesn't recognize _eidas_ data types either.
Error trace:
```
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/djangosaml2/views.py", line 460, in post
    response = client.parse_authn_request_response(
  File "/opt/app-root/lib64/python3.9/site-packages/saml2/client_base.py", line 841, in parse_authn_request_response
    resp = self._parse_response(
  File "/opt/app-root/lib64/python3.9/site-packages/saml2/entity.py", line 1496, in _parse_response
    response = response.loads(xmlstr, False, origxml=xmlstr)
  File "/opt/app-root/lib64/python3.9/site-packages/saml2/response.py", line 528, in loads
    self._loads(xmldata, decode, origxml)
  File "/opt/app-root/lib64/python3.9/site-packages/saml2/response.py", line 344, in _loads
    self.response = self.signature_check(
  File "/opt/app-root/lib64/python3.9/site-packages/saml2/sigver.py", line 1757, in correctly_signed_response
    self._check_signature(decoded_xml, response,
  File "/opt/app-root/lib64/python3.9/site-packages/saml2/sigver.py", line 1507, in _check_signature
    raise SignatureError(error_context) from e
saml2.sigver.SignatureError: {'message': 'Signature verification failed. Invalid document format.', 'reason': '"global xs:simpleType/xs:complexType \'eidas-legal:LegalPersonIdentifierType\' not found"', ...>...</saml2p:Response>'}
Forbidden: /saml2/acs/
```
We found that modifying the library, module `global_maps.py`, solved the problem. Specifically, adding the following lines in the lookup_type method:
```
    def lookup_type(self, qname: str) -> BaseXsdType:
        try:
            if qname.__contains__("LegalPersonIdentifier"):				# FROM HERE
                qname = '{http://www.w3.org/2000/09/xmldsig#}ObjectType'
            if qname.__contains__("CurrentFamily"):
                qname = '{http://www.w3.org/2000/09/xmldsig#}ObjectType'
            if qname.__contains__("CurrentGiven"):
                qname = '{http://www.w3.org/2000/09/xmldsig#}ObjectType'
            if qname.__contains__("PersonIdentifier"):
                qname = '{http://www.w3.org/2000/09/xmldsig#}ObjectType'		# TO HERE
            obj = self.types[qname]
        except KeyError:
            raise XMLSchemaKeyError(f'global xs:simpleType/xs:complexType {qname!r} not found')
        else:
            if isinstance(obj, (XsdSimpleType, XsdComplexType)):
                return obj
            return cast(BaseXsdType, self._build_global(obj, qname, self.types))
```
We don't know if from pysaml2 it is possible to parameterize the call to xmlschema or pass it some extra data so that it contemplates the validation of the new data types, in which case maybe you could help us. Otherwise, we could open an issue in the reference library:
https://github.com/sissaschool/xmlschema
Any suggestion in this regard will be welcome. Thank you!

**Comment by c00kiemon5ter** [comment]
We need to amend the eidas types so that they are recognized, but making this configurable would be better and more flexible. Then custom (stricter or less) schemas could be defined and used.

**Comment by djmm68** [comment]
It seems. There really is an open line of work on this topic. At the moment, we have modified what is necessary to make it work in our project. If it's updated in the future, we could include that update via pip, for installation in the Docker container (adjusting Docker base image). Thanks for your support @c00kiemon5ter

**Comment by c00kiemon5ter** [comment]
@djmm68 a new pysaml2 `v7.2.0` is out and includes the schema files for eIDAS. You can try using the new version without modifications on `xmlschema`. Let me know if that works for you and if you find any problems.

**Comment by djmm68** [comment]
Hi @c00kiemon5ter , Perfect!! we'll try it ASAP, and report the result to you. Maybe we can include this new version in our project.
