### ISSUE TITLE
make_metadata.py crashes with 'list object is not an iterator'

### ISSUE THREAD

**Issue by kevingolding2001** [IdentityPython/pysaml2#582]
I'm following the docs for configuring the extremely simple service provider.

When I run this command "make_metadata.py sp_conf.py > sp.xml" it crashes with this error:
```
(pysaml) kgolding@kezubuntu1604:~/pysaml/pysaml2/example/sp-wsgi$ make_metadata.py sp_conf.py > sp.xml
Traceback (most recent call last):
  File "/home/kgolding/pysaml/bin/make_metadata.py", line 4, in <module>
    __import__('pkg_resources').run_script('pysaml2==4.6.5', 'make_metadata.py')
  File "/home/kgolding/pysaml/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/kgolding/pysaml/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/home/kgolding/pysaml/lib/python2.7/site-packages/pysaml2-4.6.5-py2.7.egg/EGG-INFO/scripts/make_metadata.py", line 59, in <module>
    eds.append(entity_descriptor(cnf))
  File "/home/kgolding/pysaml/local/lib/python2.7/site-packages/pysaml2-4.6.5-py2.7.egg/saml2/metadata.py", line 725, in entity_descriptor
    _add_attr_to_entity_attributes(entd.extensions, attr)
  File "/home/kgolding/pysaml/local/lib/python2.7/site-packages/pysaml2-4.6.5-py2.7.egg/saml2/metadata.py", line 674, in _add_attr_to_entity_attributes
    extensions.extension_elements
TypeError: list object is not an iterator
```

## Code Version

The version on GitHub as of Jan 9 2019.

## Expected Behavior

According to the docs it should output some kind of xml file.
## Current Behavior

Crashes with error shown above.
## Steps to Reproduce
virtualenv pysaml
cd pysaml
. bin/activate
pip install pytest pymongo responses
git clone https://github.com/IdentityPython/pysaml2.git
cd pysaml2
python setup.py install
cd tests
py.test
cd ../example/sp-wsgi
cp sp_conf.py.example sp_conf.py
cp service_conf.py.example service_conf.py
make_metadata.py sp_conf.py > sp.xml

**Comment by c00kiemon5ter** [comment]
Hello, I cannot reproduce this. Which python version are you using? Are you sure you did not change the existing code?

**Comment by kevingolding2001** [comment]
python 2.7.12 on Ubuntu 16.04
