### ISSUE TITLE
pysaml2 4.9.0 - ERROR:saml2.client_base:XML parse error: Not for me!!!

### ISSUE THREAD

**Issue by flosoft** [IdentityPython/pysaml2#657]
## Code Version
4.9.0

## Expected Behavior
A login from via OneLogin should succeed as it did with pysaml2 4.8.0.

## Current Behavior
```
ERROR:saml2.client_base:XML parse error: Not for me!!!
--
Exception: Not for me!!!
raise Exception("Not for me!!!")
File "/usr/local/lib/python3.6/site-packages/saml2/response.py", line 616, in condition_ok
if not self.condition_ok():
File "/usr/local/lib/python3.6/site-packages/saml2/response.py", line 817, in _assertion
if not self._assertion(assertion, False):
File "/usr/local/lib/python3.6/site-packages/saml2/response.py", line 937, in parse_assertion
if self.parse_assertion(keys):
File "/usr/local/lib/python3.6/site-packages/saml2/response.py", line 1051, in verify
response = response.verify(keys)
File "/usr/local/lib/python3.6/site-packages/saml2/entity.py", line 1201, in _parse_response
binding, **kwargs)
File "/usr/local/lib/python3.6/site-packages/saml2/client_base.py", line 714, in parse_authn_request_response
entity.BINDING_HTTP_POST)
File "/usr/src/app/app.py", line 173, in idp_initiated
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
raise value
File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
Traceback (most recent call last):
During handling of the above exception, another exception occurred:
saml2.sigver.SignatureError: Signature missing for assertion
raise SignatureError("Signature missing for assertion")
File "/usr/local/lib/python3.6/site-packages/saml2/response.py", line 795, in _assertion
if not self._assertion(assertion, False):
File "/usr/local/lib/python3.6/site-packages/saml2/response.py", line 937, in parse_assertion
if self.parse_assertion(keys):
File "/usr/local/lib/python3.6/site-packages/saml2/response.py", line 1051, in verify
response = response.verify(keys)
File "/usr/local/lib/python3.6/site-packages/saml2/entity.py", line 1194, in _parse_response
Traceback (most recent call last):
ERROR:app:Exception on /saml/sso/INSTANCE.onelogin.com [POST]
```

## Possible Solution
The same code works just fine with pysaml2 4.8.0

## Steps to Reproduce
My service is based on https://github.com/jpf/okta-pysaml2-example

```
def saml_client_for(idp_name=None):
    '''
    Given the name of an IdP, return a configuation.
    The configuration is a hash for use by saml2.config.Config
    '''

    if idp_name not in metadata_url_for:
        raise Exception("Settings for IDP '{}' not found".format(idp_name))
    acs_url = url_for(
        "idp_initiated",
        idp_name=idp_name,
        _external=True)
    https_acs_url = url_for(
        "idp_initiated",
        idp_name=idp_name,
        _external=True,
        _scheme='https')

    #   SAML metadata changes very rarely. On a production system,
    #   this data should be cached as approprate for your production system.
    rv = requests.get(metadata_url_for[idp_name])

    settings = {
        'entityid': 'https://example.com/sp/metadata',
        'metadata': {
            'inline': [rv.text],
            },
        'service': {
            'sp': {
                'endpoints': {
                    'assertion_consumer_service': [
                        (acs_url, BINDING_HTTP_REDIRECT),
                        (acs_url, BINDING_HTTP_POST),
                        (https_acs_url, BINDING_HTTP_REDIRECT),
                        (https_acs_url, BINDING_HTTP_POST)
                    ],
                },
                # Don't verify that the incoming requests originate from us via
                # the built-in cache for authn request ids in pysaml2
                'allow_unsolicited': True,
                # Don't sign authn requests, since signed requests only make
                # sense in a situation where you control both the SP and IdP
                'authn_requests_signed': False,
                'logout_requests_signed': True,
                'want_assertions_signed': False,
                'want_response_signed': True,
            },
        },
    }
    spConfig = Saml2Config()
    spConfig.load(settings)
    spConfig.allow_unknown_attributes = True
    saml_client = Saml2Client(config=spConfig)
    return saml_client
```

`metadata_url_for[idp_name]` is my metadata URL from OneLogin.

**Comment by c00kiemon5ter** [comment]
You should look in the received authentication Response and check what the `<Conditions><Audience>` element contains. 

---

Also see #652:

There is a related change and it has to do with enforcing the audience restriction checks for unsolicited requests.

See, #609 and 2c3c426c7f431fe0f31cc2f67145acec31348530

**Comment by flosoft** [comment]
I just checked the SAML response, and while running the page on `localhost:5000` and 

```
            <saml:AudienceRestriction>
                <saml:Audience>localhost</saml:Audience>
            </saml:AudienceRestriction>
```

it's still failing. Any idea what the Audience URL should be instead?

I also tested with a blank value in OneLogin, resulting in:

```
            <saml:AudienceRestriction>
                <saml:Audience>{audience}</saml:Audience>
            </saml:AudienceRestriction>
```

**Comment by c00kiemon5ter** [comment]
The restriction says that only the following entities/audience should look into the Response. The `AudienceRestriction` element can have multiple `Audience` elements, one of which must have the same value as the _entityID_ of the SP. Alternatively, these are optional, so the IdP can leave them out.

**Comment by flosoft** [comment]
Ah - perfect. I found the way to resolve this.

Adding this to the settings section:
```
        'entityid': 'urn:SUBDOMAIN.DOMAIN.TLD',
```

And having the Audience in OneLogin be `urn:SUBDOMAIN.DOMAIN.TLD` as well fixes it.

Thanks for the pointers!
