### ISSUE TITLE
Entire SSO functionality ceases to work when one of the remote sp url is down.

### ISSUE THREAD

**Issue by sarthakk97** [IdentityPython/pysaml2#667]
## Code Version
We're using djangosamlidp>=0.6.2 which in turn installs version 5.0.0 of pysaml2

## Current Behavior
For our use case , we include multiple SPs and specify their respective remote metadata urls in the IDP setup. However , many of these are unreliable and are occasionally not up and running. 
In the event that one of these remote urls crashes , the entire sso functionality on the IDP's side ceases to run. 

The following error pops up. ( I'm trying to acccess the idp metadata while an sp's remote metadata url is down. )

```
[ERROR] [2020-02-10 10:19:38,210] [django.request] [log.py:228] Internal Server Error: /saml2/metadata/
Traceback (most recent call last):
  File "/Users/user1/identity_provider/nvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/user1/identity_provider/nvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/user1/identity_provider/nvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/user1/identity_provider/nvenv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/user1/identity_provider/nvenv/lib/python3.6/site-packages/djangosaml2idp/views.py", line 459, in metadata
    conf.load(copy.deepcopy(settings.SAML_IDP_CONFIG))
  File "/Users/user1/identity_provider/nvenv/lib/python3.6/site-packages/saml2/config.py", line 382, in load
    self.load_complex(cnf, metadata_construction=metadata_construction)
  File "/Users/user1/identity_provider/nvenv/lib/python3.6/site-packages/saml2/config.py", line 316, in load_complex
    self.load_metadata(cnf["metadata"]))
  File "/Users/user1/identity_provider/nvenv/lib/python3.6/site-packages/saml2/config.py", line 425, in load_metadata
    mds.imp(metadata_conf)
  File "/Users/user1/identity_provider/nvenv/lib/python3.6/site-packages/saml2/mdstore.py", line 1021, in imp
    self.load(key, **val)
  File "/Users/user1/identity_provider/nvenv/lib/python3.6/site-packages/saml2/mdstore.py", line 1009, in load
    _md.load()
  File "/Users/user1/identity_provider/nvenv/lib/python3.6/site-packages/saml2/mdstore.py", line 796, in load
    raise SourceNotFound(self.url)
saml2.mdstore.SourceNotFound: https://service-provider/sso/metadata/
```

Is there a way we can have the regular flows functional even if one of the remotes fail? So that our remaining SPs and flows can continue to work even if one of them goes down. ( While still fetching the metadata from the remote instead of keeping the metadata locally )

**Comment by mhindery** [comment]
Hi @sarthakk97 , I'm working on an update of djangosaml2idp which might help in this case. It's still a work in progress, but it is functional depending on how extensive of a featureset you need: https://github.com/OTA-Insight/djangosaml2idp/pull/51 Here I'm fetching the remote metadata and keep a local copy plus the expiry date, and if it expires I'm fetching it anew. This handles temporary downtime of the SP metadata location.

**Comment by peppelinux** [comment]
Try using a pure mdq server, like for example this:
https://github.com/UniversitaDellaCalabria/Django-MDQ

A batch pyff Will download and validate data, mdq Will serve these

**Comment by c00kiemon5ter** [comment]
I agree with @peppelinux. This is not a problem that this library should solve, but an actual MDQ service. 
I think that all parties are responsible for the metadata they consume. The metadata should be consumed by an MDQ that validates and verifies the XML docs. It should also verify that those metadata are compliant with your requirements. The MDQ, at the same time, should make sure that the metadata are refreshed often and if the other end is not available, then keep using a previous version and retry later or fail; it depends on your policy. 
Making all of this the responsibility of the library seems out of scope.

**Comment by peppelinux** [comment]
Yes, things we know, because they are already tested.

The important thing in this thread is that a Remote MDStore should be used only for a SP with a single IDP. Because that MDStore will do a http request  to that IdP's metadata url, on each incoming http... It's a PAIN.

A smart solution would be instead using a Remote MDStore that stores those metadata in the filesystem and refresh them with CacheDuration and validUntil parameters.

But we are getting older and the MDQ is the stop application for this kind of things.
So do not use REMOTE MDSTORE in IdP for any reason!

And more... We could have a circular dependency between a IdP that have a remote mdstore to a SP that have a remote MDstore to that IdP. The IdP will not release its metadata untill its MDstore will be initialized, in other words: until the SP will give its metadata. This latter the same...so, both of them will go in timeout and error 500. 

Bad news, this would be patched, documented or something
