### ISSUE TITLE
Errors in IDP example

### ISSUE THREAD

**Issue by webmaxttor** [IdentityPython/pysaml2#817]
Following the [documentation](https://pysaml2.readthedocs.io/en/latest/examples/sp.html) to setup the WSGI example ist not working.

## Code Version
master - v 7.0.1

## Expected Behavior
Login successful

## Steps to Reproduce
- config the idp following the doc (wgsi only)
- config the sp  following the doc (wgsi only)
- start idp - Ok
- start sp - Ok
- access SP - Ok
- Redirect to idp e.g. (https://localhost:8088/sso/redirect?SAMLRequest=(...)&RelayState=(...)&SigAlg=(...)&Signature=(...) ) - Ok
- try to login with: user: daev0001, pwd: qwerty
- Error:  500 (KeyError: None)

Traceback:

```
[2021-08-05 16:09:09,492] [DEBUG] [saml2.mdstore.service] service => [{'__class__': 'urn:oasis:names:tc:SAML:2.0:metadata&AssertionConsumerService', 'binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST', 'location': 'http://localhost:8087/acs/post', 'index': '1'}]
KeyError(None)
Traceback (most recent call last):
  File "/home/rodrigo/.virtualenvs/refline_webseite/lib/python3.8/site-packages/cheroot/server.py", line 1287, in communicate
    req.respond()
  File "/home/rodrigo/.virtualenvs/refline_webseite/lib/python3.8/site-packages/cheroot/server.py", line 1077, in respond
    self.server.gateway(self).respond()
  File "/home/rodrigo/.virtualenvs/refline_webseite/lib/python3.8/site-packages/cheroot/wsgi.py", line 140, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "idp.py", line 1082, in application
    return func()
  File "idp.py", line 447, in redirect
    return self.operation(saml_msg, BINDING_HTTP_REDIRECT)
  File "idp.py", line 172, in operation
    return self.do(saml_msg["SAMLRequest"], binding, **kwargs)
  File "idp.py", line 341, in do
    identity = USERS[self.user].copy()
KeyError: None

```

**Comment by peppelinux** [comment]
self.user Is None

Take a look in the class __init__ to see how it's valued

**Comment by c00kiemon5ter** [comment]
Hello @webmaxttor,

you are looking at the `PASSWD` struct defined here:
- https://github.com/IdentityPython/pysaml2/blob/082f8ed/example/idp2/idp.py#L551-L557

but, the users behind the IdP are the ones defined here:
- https://github.com/IdentityPython/pysaml2/blob/082f8ed/example/idp2/idp_user.py#L37

the credentials for the users are defined by `PASSWD`. 

> try to login with: user: daev0001, pwd: qwerty

Based on the above, all other users should just work.

Let me know if that works for you.
