### ISSUE TITLE
IdP fails with SignatureError when parsing remote metadata for SP

### ISSUE THREAD

**Issue by bjm88** [IdentityPython/pysaml2#845]
Latest code/library, testing on MacOS local dev and Amazon Linux.  Generally PySAML2 is working for us being an IDP and SP.  
For metadata found here, https://mychart-np.atlantichealth.org/mychartpoc/Authentication/Saml/Metadata that we believe is valid, we are getting a `saml2.sigver.SignatureError` error when initializing in our code at:

```py
saml2_config = Saml2Config()
saml2_config.load(idpSettings)
```

Our idp settings are typical

```py
IDP_CONFIG = {
        "entityid": BASE + "/saml/sso/idp",
        "description": "My IDP",
        #"valid_for": 168,
        "service": {
            "idp": {
```

outside of the idp config node though we have this

```py
        "delete_tmpfiles": False, #TODO change to True
        "verify_ssl_cert": False, #TODO change to True
        "metadata": {
            "remote": [
                {
                    "url": "https://mychart-np.atlantichealth.org/mychartpoc/Authentication/Saml/Metadata",
                    "cert": "./app/python_api/resolvers/mychart_sp_poc_combo_cert.pem",
                    "disable_ssl_certificate_validation": True, #TODO change
                    "check_validity": False,
                    "verify_ssl_cert": False, #TODO change to True,
                    "signing_algorithm": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
                },
            ],
        },
```

It didn't seem like the verify False setting was working to simply see if we could bypass this to confirm no other issues.  More important we were unable to see why this signature algo was failing.  Do we need to specify the algorithm somehow or not?  The metadata actually states the signature and what algo it uses.  Any help on this would be greatly appreciated, as well as if there is any 3rd party free online service to simply verify a full metadata file, including its signature.  Didn't see this in samltools.com.  thx.

Any thoughts @c00kiemon5ter ?

```
[2021-12-14 21:43:28,603] [DEBUG] [saml2.httpbase.send] GET to https://mychart-np.atlantichealth.org/mychartpoc/Authentication/Saml/Metadata
[2021-12-14 21:43:28,791] [DEBUG] [saml2.httpbase.send] Response status: 200
[2021-12-14 21:43:28,797] [DEBUG] [saml2.sigver._run_xmlsec] xmlsec command: /usr/local/bin/xmlsec1 --verify --enabled-reference-uris empty,same-doc --enabled-key-data raw-x509-cert --pubkey-cert-pem /Users/benjaminmaisano/dev/atlantichealth/digital-front-door/python/app/python_api/resolvers/mychart_sp_poc_combo_cert.pem --id-attr:ID urn:oasis:names:tc:SAML:2.0:metadata:EntitiesDescriptor --output /var/folders/zj/0j90r53n281d0fzghl872w5r0000gn/T/tmpkyj6ojob.xml /var/folders/zj/0j90r53n281d0fzghl872w5r0000gn/T/tmp7zx0o0o9.xml
[2021-12-14 21:43:28,827] [ERROR] [saml2.sigver._run_xmlsec] returncode=1
error=func=xmlSecXPathDataExecute:file=xpath.c:line=247:obj=unknown:subj=xmlXPtrEval:error=5:libxml2 library function failed:expr=xpointer(id('id02feaf8a081541c8bbf8c76158b0aa48')); xml error: 0: NULL
func=xmlSecXPathDataListExecute:file=xpath.c:line=330:obj=unknown:subj=xmlSecXPathDataExecute:error=1:xmlsec library function failed: 
func=xmlSecTransformXPathExecute:file=xpath.c:line=431:obj=xpointer:subj=xmlSecXPathDataListExecute:error=1:xmlsec library function failed: 
func=xmlSecTransformDefaultPushXml:file=transforms.c:line=2109:obj=xpointer:subj=xmlSecTransformExecute:error=1:xmlsec library function failed: 
func=xmlSecTransformCtxXmlExecute:file=transforms.c:line=1045:obj=xpointer:subj=xmlSecTransformPushXml:error=1:xmlsec library function failed: 
func=xmlSecTransformCtxExecute:file=transforms.c:line=1092:obj=unknown:subj=xmlSecTransformCtxXmlExecute:error=1:xmlsec library function failed: 
func=xmlSecDSigReferenceCtxProcessNode:file=xmldsig.c:line=1409:obj=unknown:subj=xmlSecTransformCtxExecute:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxProcessReferences:file=xmldsig.c:line=753:obj=Reference:subj=xmlSecDSigReferenceCtxProcessNode:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=517:obj=unknown:subj=xmlSecDSigCtxProcessReferences:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxVerify:file=xmldsig.c:line=346:obj=unknown:subj=xmlSecDSigCtxProcessSignatureNode:error=1:xmlsec library function failed: 
Error: signature failed 
ERROR
SignedInfo References (ok/all): 0/1
Manifests References (ok/all): 0/0
Error: failed to verify file "/var/folders/zj/0j90r53n281d0fzghl872w5r0000gn/T/tmp7zx0o0o9.xml"

output=
[2021-12-14 21:43:28,830] [ERROR] [app.log_exception] Exception on /samlsso/idp/init-unsolicited-response [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/saml2/sigver.py", line 893, in validate_signature
    (_stdout, stderr, _output) = self._run_xmlsec(com_list, [tmp.name])
  File "/usr/local/lib/python3.9/site-packages/saml2/sigver.py", line 923, in _run_xmlsec
    raise XmlsecError(errmsg)
saml2.sigver.XmlsecError: returncode=1
error=func=xmlSecXPathDataExecute:file=xpath.c:line=247:obj=unknown:subj=xmlXPtrEval:error=5:libxml2 library function failed:expr=xpointer(id('id02feaf8a081541c8bbf8c76158b0aa48')); xml error: 0: NULL
func=xmlSecXPathDataListExecute:file=xpath.c:line=330:obj=unknown:subj=xmlSecXPathDataExecute:error=1:xmlsec library function failed: 
func=xmlSecTransformXPathExecute:file=xpath.c:line=431:obj=xpointer:subj=xmlSecXPathDataListExecute:error=1:xmlsec library function failed: 
func=xmlSecTransformDefaultPushXml:file=transforms.c:line=2109:obj=xpointer:subj=xmlSecTransformExecute:error=1:xmlsec library function failed: 
func=xmlSecTransformCtxXmlExecute:file=transforms.c:line=1045:obj=xpointer:subj=xmlSecTransformPushXml:error=1:xmlsec library function failed: 
func=xmlSecTransformCtxExecute:file=transforms.c:line=1092:obj=unknown:subj=xmlSecTransformCtxXmlExecute:error=1:xmlsec library function failed: 
func=xmlSecDSigReferenceCtxProcessNode:file=xmldsig.c:line=1409:obj=unknown:subj=xmlSecTransformCtxExecute:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxProcessReferences:file=xmldsig.c:line=753:obj=Reference:subj=xmlSecDSigReferenceCtxProcessNode:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=517:obj=unknown:subj=xmlSecDSigCtxProcessReferences:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxVerify:file=xmldsig.c:line=346:obj=unknown:subj=xmlSecDSigCtxProcessSignatureNode:error=1:xmlsec library function failed: 
Error: signature failed 
ERROR
SignedInfo References (ok/all): 0/1
Manifests References (ok/all): 0/0
Error: failed to verify file "/var/folders/zj/0j90r53n281d0fzghl872w5r0000gn/T/tmp7zx0o0o9.xml"

output=

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/benjaminmaisano/dev/atlantichealth/digital-front-door/python/app/python_api/routes/sso_routes.py", line 194, in saml_sso_idp_unsolicited_response
    saml2_config = saml_sso_idp_get_config()
  File "/Users/benjaminmaisano/dev/atlantichealth/digital-front-door/python/app/python_api/routes/sso_routes.py", line 264, in saml_sso_idp_get_config
    saml2_config.load(idpSettings)
  File "/usr/local/lib/python3.9/site-packages/saml2/config.py", line 337, in load
    self.load_complex(cnf)
  File "/usr/local/lib/python3.9/site-packages/saml2/config.py", line 271, in load_complex
    self.setattr("", "metadata", self.load_metadata(cnf["metadata"]))
  File "/usr/local/lib/python3.9/site-packages/saml2/config.py", line 387, in load_metadata
    mds.imp(metadata_conf)
  File "/usr/local/lib/python3.9/site-packages/saml2/mdstore.py", line 1081, in imp
    self.load(key, **val)
  File "/usr/local/lib/python3.9/site-packages/saml2/mdstore.py", line 1069, in load
    _md.load()
  File "/usr/local/lib/python3.9/site-packages/saml2/mdstore.py", line 853, in load
    return self.parse_and_check_signature(_txt)
  File "/usr/local/lib/python3.9/site-packages/saml2/mdstore.py", line 747, in parse_and_check_signature
    return self.security.verify_signature(
  File "/usr/local/lib/python3.9/site-packages/saml2/sigver.py", line 1418, in verify_signature
    return self.crypto.validate_signature(
  File "/usr/local/lib/python3.9/site-packages/saml2/sigver.py", line 895, in validate_signature
    six.raise_from(SignatureError(com_list), e)
  File "<string>", line 3, in raise_from
saml2.sigver.SignatureError: ['/usr/local/bin/xmlsec1', '--verify', '--enabled-reference-uris', 'empty,same-doc', '--enabled-key-data', 'raw-x509-cert', '--pubkey-cert-pem', '/Users/benjaminmaisano/dev/atlantichealth/digital-front-door/python/app/python_api/resolvers/mychart_sp_poc_combo_cert.pem', '--id-attr:ID', 'urn:oasis:names:tc:SAML:2.0:metadata:EntitiesDescriptor', '--output', '/var/folders/zj/0j90r53n281d0fzghl872w5r0000gn/T/tmpkyj6ojob.xml', '/var/folders/zj/0j90r53n281d0fzghl872w5r0000gn/T/tmp7zx0o0o9.xml']
```

**Comment by bjm88** [comment]
Ok I found issue, but not sure how to fix through pysaml2 yet.  This thread helped m/qEt7455u/error-libxml2-library-function-failed-expr-xpointer

Basically the xmlsec1 --verify command seems to care about the --id-attr:ID and mapping it to the right namespace, so in my case the SP metadata looks like this..
<q1:EntityDescriptor xmlns:q1="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://mychart-np.atlantichealth.org/MyChartPOC" validUntil="2021-12-22T02:43:28.8444050Z" ID="id02feaf8a081541c8bbf8c76158b0aa48">
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">

So xmlsec1 to verify is expecting "--id-attr:ID urn:oasis:names:tc:SAML:2.0:metadata:EntityDescriptor" to pass.  However pysaml2 is passing
--id-attr:ID urn:oasis:names:tc:SAML:2.0:metadata:EntitiesDescriptor

Metadata can have list of metadata:EntityDescriptor where I assume EntitiesDescriptor is the parent.  Not sure how to tell pysaml2 this sp just lists one metadata:EntityDescriptor......??


pysaml2's generated call isthis and fails
/usr/local/bin/xmlsec1 --verify --enabled-reference-uris empty,same-doc --enabled-key-data raw-x509-cert --pubkey-cert-pem /Users/benjaminmaisano/dev/atlantichealth/digital-front-door/python/app/python_api/resolvers/mychart_sp_poc_combo_cert.pem --id-attr:ID urn:oasis:names:tc:SAML:2.0:metadata:EntitiesDescriptor --output /var/folders/zj/0j90r53n281d0fzghl872w5r0000gn/T/tmpkyj6ojob.xml /var/folders/zj/0j90r53n281d0fzghl872w5r0000gn/T/tmp7zx0o0o9.xml

I can run this manually and it works..
 /usr/local/bin/xmlsec1 --verify --enabled-reference-uris empty,same-doc --enabled-key-data raw-x509-cert --pubkey-cert-pem /Users/benjaminmaisano/dev/atlantichealth/digital-front-door/python/app/python_api/resolvers/mychart_sp_poc_combo_cert.pem --id-attr:ID urn:oasis:names:tc:SAML:2.0:metadata:EntityDescriptor --output /var/folders/zj/0j90r53n281d0fzghl872w5r0000gn/T/tmpkyj6ojob.xml /var/folders/zj/0j90r53n281d0fzghl872w5r0000gn/T/tmp7zx0o0o9.xml

help please! thx.

**Comment by bjm88** [comment]
Also finding this fix is related
https://github.com/IdentityPython/pysaml2/pull/662
but not exactly what I need.  Also not finding anything in docs that talk about how to control this.  I'd think it automatically knows its looking at a node that is
EntityDescriptor 
instead of
EntitiesDescriptor

I am not trying to change the "--id-attr:ID" part of the xmlsec1 command, the :"ID" is fine, its the node name that is misaligned and not sure how to configure override...

**Comment by c00kiemon5ter** [comment]
This issue is that the metadata document is expected to have an `EntitiesDescriptor` root node, but the metadata document only has an `EntityDescriptor`. With the latest commits both cases are checked and should fix this issue.

**Comment by c00kiemon5ter** [comment]
@bjm88 can we close this one too?

**Comment by sibin-impress** [comment]
@bjm88 How you resolved this issue ?
Could you help me with the same ? I’m also getting error in production related to the pysaml2==7.1.0 as following 
```

returncode=1
error=func=xmlSecOpenSSLEvpSignatureVerify:file=evp_signatures.c:line=368:obj=rsa-sha256:subj=unknown:error=18:data do not match:details=EVP_VerifyFinal: signature does not verify
FAIL
SignedInfo References (ok/all): 1/1
Manifests References (ok/all): 0/0
Error: failed to verify file "/tmp/tmp9knzoqj8.xml"

output=
```
