### ISSUE TITLE
To generate `idp.xml`, it needs `sp.xml` and vise versa.

### ISSUE THREAD

**Issue by omidraha** [IdentityPython/pysaml2#849]
To generate `idp.xml`, it needs `sp.xml` and vise versa.

**Reproduce:**

``` bash 
git clone https://github.com/IdentityPython/pysaml2/
cd pysaml2/example
./all.sh start 
```

**Info**:

```Python
pip install pysaml2

sudo apt-get install xmlsec1

pip freeze | grep pysaml2

pysaml2==7.1.0
```

**Traceback:**
```
pysaml2/example$ ./all.sh start

Traceback (most recent call last):
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1700, in close
    self.parser.Parse("", 1) # end of data
xml.parsers.expat.ExpatError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 615, in parse
    self.entities_descr = md.entities_descriptor_from_string(xmlstr)
  File "venv/lib/python3.8/site-packages/saml2/md.py", line 1859, in entities_descriptor_from_string
    return saml2.create_class_from_xml_string(EntitiesDescriptor, xml_string)
  File "venv/lib/python3.8/site-packages/saml2/__init__.py", line 100, in create_class_from_xml_string
    tree = defusedxml.ElementTree.fromstring(xml_string)
  File "venv/lib/python3.8/site-packages/defusedxml/common.py", line 132, in fromstring
    return parser.close()
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1702, in close
    self._raiseerror(v)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1602, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../../tools/make_metadata.py", line 56, in <module>
    cnf = Config().load_file(fil)
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 367, in load_file
    return self.load(copy.deepcopy(mod.CONFIG))
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 338, in load
    self.load_complex(cnf)
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 272, in load_complex
    self.setattr("", "metadata", self.load_metadata(cnf["metadata"]))
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 388, in load_metadata
    mds.imp(metadata_conf)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 1086, in imp
    self.load(key, val)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 1072, in load
    _md.load()
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 774, in load
    return self.parse_and_check_signature(_txt)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 737, in parse_and_check_signature
    self.parse(txt)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 624, in parse
    raise SAMLError(f'Failed to parse {_md_desc}') from e
saml2.SAMLError: Failed to parse metadata file: ../idp2/idp.xml
Traceback (most recent call last):
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1700, in close
    self.parser.Parse("", 1) # end of data
xml.parsers.expat.ExpatError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 615, in parse
    self.entities_descr = md.entities_descriptor_from_string(xmlstr)
  File "venv/lib/python3.8/site-packages/saml2/md.py", line 1859, in entities_descriptor_from_string
    return saml2.create_class_from_xml_string(EntitiesDescriptor, xml_string)
  File "venv/lib/python3.8/site-packages/saml2/__init__.py", line 100, in create_class_from_xml_string
    tree = defusedxml.ElementTree.fromstring(xml_string)
  File "venv/lib/python3.8/site-packages/defusedxml/common.py", line 132, in fromstring
    return parser.close()
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1702, in close
    self._raiseerror(v)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1602, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../../tools/make_metadata.py", line 56, in <module>
    cnf = Config().load_file(fil)
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 367, in load_file
    return self.load(copy.deepcopy(mod.CONFIG))
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 338, in load
    self.load_complex(cnf)
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 272, in load_complex
    self.setattr("", "metadata", self.load_metadata(cnf["metadata"]))
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 388, in load_metadata
    mds.imp(metadata_conf)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 1086, in imp
    self.load(key, val)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 1072, in load
    _md.load()
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 774, in load
    return self.parse_and_check_signature(_txt)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 737, in parse_and_check_signature
    self.parse(txt)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 624, in parse
    raise SAMLError(f'Failed to parse {_md_desc}') from e
saml2.SAMLError: Failed to parse metadata file: /git/pysaml2/example/idp2/../sp-wsgi/sp.xml
(venv) git/pysaml2/example$ Traceback (most recent call last):
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1700, in close
    self.parser.Parse("", 1) # end of data
xml.parsers.expat.ExpatError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 615, in parse
    self.entities_descr = md.entities_descriptor_from_string(xmlstr)
  File "venv/lib/python3.8/site-packages/saml2/md.py", line 1859, in entities_descriptor_from_string
    return saml2.create_class_from_xml_string(EntitiesDescriptor, xml_string)
  File "venv/lib/python3.8/site-packages/saml2/__init__.py", line 100, in create_class_from_xml_string
    tree = defusedxml.ElementTree.fromstring(xml_string)
  File "venv/lib/python3.8/site-packages/defusedxml/common.py", line 132, in fromstring
    return parser.close()
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1702, in close
    self._raiseerror(v)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1602, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./sp.py", line 973, in <module>
    SP = Saml2Client(config_file="%s" % CNFBASE)
  File "venv/lib/python3.8/site-packages/saml2/client_base.py", line 158, in __init__
    Entity.__init__(self, "sp", config, config_file, virtual_organization,
  File "venv/lib/python3.8/site-packages/saml2/entity.py", line 141, in __init__
    self.config = config_factory(entity_type, config_file)
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 511, in config_factory
    conf.load_file(config)
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 367, in load_file
    return self.load(copy.deepcopy(mod.CONFIG))
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 338, in load
    self.load_complex(cnf)
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 272, in load_complex
    self.setattr("", "metadata", self.load_metadata(cnf["metadata"]))
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 388, in load_metadata
    mds.imp(metadata_conf)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 1086, in imp
    self.load(key, val)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 1072, in load
    _md.load()
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 774, in load
    return self.parse_and_check_signature(_txt)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 737, in parse_and_check_signature
    self.parse(txt)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 624, in parse
    raise SAMLError(f'Failed to parse {_md_desc}') from e
saml2.SAMLError: Failed to parse metadata file: ../idp2/idp.xml
Traceback (most recent call last):
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1700, in close
    self.parser.Parse("", 1) # end of data
xml.parsers.expat.ExpatError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 615, in parse
    self.entities_descr = md.entities_descriptor_from_string(xmlstr)
  File "venv/lib/python3.8/site-packages/saml2/md.py", line 1859, in entities_descriptor_from_string
    return saml2.create_class_from_xml_string(EntitiesDescriptor, xml_string)
  File "venv/lib/python3.8/site-packages/saml2/__init__.py", line 100, in create_class_from_xml_string
    tree = defusedxml.ElementTree.fromstring(xml_string)
  File "venv/lib/python3.8/site-packages/defusedxml/common.py", line 132, in fromstring
    return parser.close()
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1702, in close
    self._raiseerror(v)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1602, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./idp.py", line 1124, in <module>
    IDP = server.Server(args.config, cache=Cache())
  File "venv/lib/python3.8/site-packages/saml2/server.py", line 89, in __init__
    Entity.__init__(self, stype, config, config_file, msg_cb=msg_cb)
  File "venv/lib/python3.8/site-packages/saml2/entity.py", line 141, in __init__
    self.config = config_factory(entity_type, config_file)
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 511, in config_factory
    conf.load_file(config)
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 367, in load_file
    return self.load(copy.deepcopy(mod.CONFIG))
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 338, in load
    self.load_complex(cnf)
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 272, in load_complex
    self.setattr("", "metadata", self.load_metadata(cnf["metadata"]))
  File "venv/lib/python3.8/site-packages/saml2/config.py", line 388, in load_metadata
    mds.imp(metadata_conf)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 1086, in imp
    self.load(key, val)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 1072, in load
    _md.load()
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 774, in load
    return self.parse_and_check_signature(_txt)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 737, in parse_and_check_signature
    self.parse(txt)
  File "venv/lib/python3.8/site-packages/saml2/mdstore.py", line 624, in parse
    raise SAMLError(f'Failed to parse {_md_desc}') from e
saml2.SAMLError: Failed to parse metadata file: /git/pysaml2/example/idp2/../sp-wsgi/sp.xml


```
**Fixed:**

[Fixed](https://github.com/IdentityPython/pysaml2/issues/737#issuecomment-754939360) by sample generated idp.xml.

And also there is a related log after that:
```
Entity descriptor (entity id:https://localhost:8088/idp.xml) too old
```

**Comment by c00kiemon5ter** [comment]
An `idp.xml` file is included in the examples (under `examples/idp2/`) since v7.1.0 (by d88ad14d818ade2ea06c9c7823fca32eb878cea9)

```bash
# clone repo and enter examples
$ git clone https://github.com/IdentityPython/pysaml2.git
$ cd pysaml2/example

# setup environment and deps
$ python3 -m venv venv
$ . venv/bin/activate
$ pip install -U pip setuptools wheel
$ pip install -U pysaml2 -r requirements.txt

# ready to run
$ ./all.sh start
...
SP listening on localhost:8087
...
IDP listening on localhost:8088
```

I will close this, but 
- make sure you have pulled the latest master
- feel free to add more information if this is not working for you

**Comment by omidraha** [comment]
Thanks, but now I have this [second](https://github.com/IdentityPython/pysaml2/issues/844#issuecomment-1003751000) issue.

**Comment by omidraha** [comment]
@c00kiemon5ter
